apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client-side-lb-headless-svc
  labels:
    app: grpc-client-side-lb-headless-svc
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grpc-client-side-lb-headless-svc
  template:
    metadata:
      labels:
        app: grpc-client-side-lb-headless-svc
    spec:
      containers:
        - name: grpc-client-side-lb-headless-svc
          command:
            - /shaouai/bin/server_bin
          image: registry-vpc.cn-zhangjiakou.aliyuncs.com/shaouai/grpc-client-side-lb-server:git.bf1a79e82318e651e796642f9ceea22d6dbd8787
      imagePullSecrets:
        - name: acr-zhangjiakou

---

apiVersion: v1
kind: Service
metadata:
  name: grpc-client-side-lb-headless-svc
  namespace: default
spec:
  selector:
    app: grpc-client-side-lb-headless-svc
  clusterIP: None
