apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client-side-lb-client
  labels:
    app: grpc-client-side-lb-client
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grpc-client-side-lb-client
  template:
    metadata:
      labels:
        app: grpc-client-side-lb-client
    spec:
      containers:
        - name: grpc-client-side-lb-client
          command:
            - /shaouai/bin/client_bin
          image: registry-vpc.cn-zhangjiakou.aliyuncs.com/shaouai/grpc-client-side-lb-client:git.2ce0feee86da51493835910347dd314130e20646
      imagePullSecrets:
        - name: acr-zhangjiakou

---

apiVersion: v1
kind: Service
metadata:
  name: grpc-client-side-lb-client
  namespace: default
spec:
  type: NodePort
  selector:
    app: grpc-client-side-lb-client
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
